### ISSUE TITLE
Karma Gate Crash

### ISSUE THREAD

**Issue by BlazingFieryMountain** [SchuhBaum/SBCameraScroll#10]
When I go through the karma gate between Shaded Citadel and Shoreline (entering from Shoreline) (Survivor's campaign) I crash. I don't know if this is a Survivor-only bug or just for that karma gate (this is the first ive gone through after downloading the mod) but im sad please send help

**Comment by SchuhBaum** [comment]
Well, you need to let it do its thing (see FAQ question 3).
