### ISSUE TITLE
Game gets stuck on the loading screen when trying to enter an arena or campaign

### ISSUE THREAD

**Issue by Dukemz** [SchuhBaum/SBCameraScroll#11]
Game version: v1.9.07b
No mods installed except for No Mod Update Confirm, disabling this still causes the same issue.

[exceptionLog.txt](https://github.com/SchuhBaum/SBCameraScroll/files/15221298/exceptionLog.txt)
[consoleLog.txt](https://github.com/SchuhBaum/SBCameraScroll/files/15221314/consoleLog.txt)

**Comment by SchuhBaum** [comment]
What version of the game are you on? You have SBCameraScroll v2.8.1. So you need Rain World v1.9.15.

The error that you get is that the modding files don't match what the mod is expecting (i.e., what it was compiled with). If you are on Rain World ~1.9.7 then you need SBCameraScroll v2.7.7 or earlier (see https://github.com/SchuhBaum/SBCameraScroll/releases).

**Comment by Dukemz** [comment]
Oops, that seems to be it. The mod didn't show the target game version for some reason so I got a bit confused, my mistake. Thanks!

**Comment by SchuhBaum** [comment]
Yeah. I have added a target version only recently. So the confusion is my bad. You are not the only one.
Have fun!
