### ISSUE TITLE
Beastmaster Offset

### ISSUE THREAD

**Issue by astrolauncherisntworking** [SchuhBaum/SBCameraScroll#9]
It offsets the menu of beastmaster (AKA it moves the actual position of the menu buttons to the left a ton, being in a different place than the visual button locations), I know it's this mod because I disabled it and Beastmaster reset, it happens in all rooms, and it is just these 2 mods.

**Comment by SchuhBaum** [comment]
Here is a video of what I am seeing: https://www.youtube.com/watch?v=eQ0Ff7IzG3A
It looks normal to me. Or can you point out where the bug happens in the video? It is also strange that it happens in all rooms. Camera scroll is disabled by default in one-screen rooms.

Maybe you can provide the debug logs as described in the section BUG REPORTS. There might be things that the game is complaining about in these logs.

**Comment by astrolauncherisntworking** [comment]
Will do, I don't know where debug logs are though...

**Comment by SchuhBaum** [comment]
The relative paths are describes in the section BUG REPORTS. Your Rain World folder path is something like: ..\Steam\SteamApps\common\Rain World\

**Comment by astrolauncherisntworking** [comment]
All the sudden when I need an example it wants to work... Thank you for helping though.
